In [23]:
import numpy as np
import pandas as pd

In [10]:
Student_ID = np.arange(1, 101)
Student_ID

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [11]:
Sex = np.random.randint(0,2, size = 100)
Sex   

array([1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1])

In [12]:
Math_Score = np.random.randint(0, 101, size = 100)
Math_Score

array([32, 49, 27, 25, 47, 37, 68, 70, 81, 83, 17, 15,  9, 34, 24, 19, 82,
       13, 64, 28, 42, 20, 64, 27, 42, 68, 54, 19, 17, 46, 99, 23, 49, 89,
       82, 51,  8, 38, 69, 43, 83, 26, 20, 29, 82, 12, 25,  9, 50, 54, 44,
       69, 42, 91, 53, 23, 68, 18, 24, 75, 91, 81, 21, 52,  5, 24, 13, 11,
       22, 16, 91, 66, 15,  1, 48, 74, 86, 53, 63, 66, 91, 72, 70, 53, 84,
       66, 69, 60, 65, 59, 56,  6, 46, 90, 14, 21, 63, 52, 16, 66])

In [28]:
student_data = np.column_stack((Student_ID, Sex,Math_Score))


df = pd.DataFrame({
    "Student ID": Student_ID,
    "Sex": Sex,
    "Math Score": Math_Score
})

# display the DataFrame
df[0:5]



Student ID  Sex  Math Score
0           1    1          32
1           2    0          49
2           3    0          27
3           4    0          25
4           5    1          47

## Mean of scores 

In [29]:
Mean = np.mean(student_data[:,2])
print("Mean of Student is:", Mean)


Mean of Student is: 46.89


## Median score

In [55]:
median = np.median(student_data[:,2])
print("Median of Student is :", median)


Median of Student is : 44.0


## Standard Deviation 

In [14]:
Std = np.std((student_data[:,2]))
print("Standard deviation of Student is :", Std)

Standard deviation of Student is : 26.240767900349255


## Highest score

In [57]:
Max = np.max((student_data[:,2]))
print("The highest Student Scored :", Max)


The highest Student Scroed : 98


## Lowest score

In [15]:
Lowest = np.min((student_data[:,2]))
print("The Student with the lowest Score:", Lowest)

The Student with the lowest Score: 1


## Total number male

In [16]:
# 1 Represent males

Total_Male  = np.count_nonzero((student_data[:,1] == 1))

print("Total number of males:", Total_Male)


Total number of males: 47


## Total number Females 

In [17]:
Total_Female = np.count_nonzero((student_data[:,1] == 0))

print("Total number of males:", Total_Female)

Total number of males: 53



## Top 10 Male Student 



In [39]:


male_students = df[df["Sex"] == 1]
# Sort the male students by their math scores in descending order


# sort the male students by math score in descending order
sorted_male_df = male_df.sort_values(by="Math Score", ascending=False)

# display the sorted data
print(sorted_male_df)



    Student ID  Sex  Math Score
30          31    0          99
53          54    0          91
33          34    0          89
76          77    0          86
40          41    0          83
44          45    0          82
34          35    0          82
16          17    0          82
61          62    0          81
75          76    0          74
81          82    0          72
51          52    0          69
86          87    0          69
38          39    0          69
56          57    0          68
79          80    0          66
71          72    0          66
88          89    0          65
22          23    0          64
78          79    0          63
87          88    0          60
49          50    0          54
83          84    0          53
54          55    0          53
63          64    0          52
97          98    0          52
35          36    0          51
1            2    0          49
32          33    0          49
92          93    0          46
20      

## Top 10 Females Student 

In [19]:

# I wanted the use the np.where function but i was not getting it 
Female_students = student_data[student_data[:, 1] == 0]


# Sort the Female students by their math scores in descending order
Female_students_descending = Female_students[Female_students[:, 2].argsort()[::-1]]

Female_students_descending [:10]

array([[31,  0, 99],
       [54,  0, 91],
       [34,  0, 89],
       [77,  0, 86],
       [41,  0, 83],
       [17,  0, 82],
       [45,  0, 82],
       [35,  0, 82],
       [62,  0, 81],
       [76,  0, 74]])